# Generated by Django 4.0.3 on 2022-05-02 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_type', models.IntegerField(choices=[(0, 'Dislike'), (1, 'Like')])),
            ],
        ),
        migrations.AddField(
            model_name='questions',
            name='users_reactions',
            field=models.ManyToManyField(related_name='reacted_on_question', through='questions.QuestionReaction', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='questions',
            name='author_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='questions',
            name='status',
            field=models.IntegerField(choices=[(1, 'Opened'), (0, 'Closed')], default=1),
        ),
        migrations.AddField(
            model_name='questionreaction',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.questions'),
        ),
        migrations.AddField(
            model_name='questionreaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
