# Generated by Django 4.0.3 on 2022-04-09 08:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='date_of_publication',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 9, 11, 59, 22, 974376)),
        ),
    ]
