# Generated by Django 4.0.3 on 2022-04-09 09:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_alter_questions_date_of_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='date_of_publication',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 9, 12, 21, 6, 506489)),
        ),
    ]
