# Generated by Django 4.0.3 on 2022-04-12 18:28

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_alter_questions_date_of_publication'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=40, validators=[django.core.validators.RegexValidator(regex='^#[a-zA-Z0-9#\\+\\-]{1,40}')])),
            ],
        ),
        migrations.AlterField(
            model_name='questions',
            name='date_of_publication',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 12, 21, 28, 53, 610112)),
        ),
        migrations.AddField(
            model_name='questions',
            name='tags',
            field=models.ManyToManyField(to='questions.tags'),
        ),
    ]
