# Generated by Django 4.0.3 on 2022-04-12 18:35

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_tags_alter_questions_date_of_publication_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='date_of_publication',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 12, 21, 35, 8, 187691)),
        ),
        migrations.AlterField(
            model_name='tags',
            name='tag_name',
            field=models.CharField(max_length=40, unique=True, validators=[django.core.validators.RegexValidator(regex='^#[a-zA-Z0-9#\\+\\-]{1,40}')]),
        ),
    ]
