# Generated by Django 4.0.3 on 2022-04-16 22:33

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_body', models.CharField(max_length=1500, validators=[django.core.validators.MinLengthValidator(20)])),
                ('date_of_publication', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('number_of_likes', models.IntegerField(blank=True, default=0)),
                ('number_of_dislikes', models.IntegerField(blank=True, default=0)),
                ('fame_index', models.FloatField(blank=True, default=1)),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.questions')),
            ],
        ),
    ]
