# Generated by Django 4.0.3 on 2022-04-13 14:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='date_of_publication',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 13, 17, 47, 37, 333647)),
        ),
    ]
