# Generated by Django 4.0.3 on 2022-05-02 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
        ('answers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_type', models.IntegerField(choices=[(0, 'Dislike'), (1, 'Like')])),
            ],
        ),
        migrations.AddField(
            model_name='answers',
            name='users_reactions',
            field=models.ManyToManyField(related_name='reacted_on_answer', through='answers.AnswerReaction', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='answers',
            name='author_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answerreaction',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='answers.answers'),
        ),
        migrations.AddField(
            model_name='answerreaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
